profiles:
   - base.sb
   - homebrew.sb
   - project.sb
   - knauf.sb
   - tools/ssh.sb
   - tools/git.sb
   - tools/open.sb
   - tools/gh.sb
   - tools/pup.sb
   - tools/pas-cli.sb
   - tools/sonar.sb
   - tools/snyk-cli.sb
   - tools/docker.sb
   - tools/node.sb
   - tools/python.sb
   - tools/cargo.sb
   - tools/nvim.sb
   - agents/pi.sb
   - tools/plannotator.sb

allow:
  read:
    - ~/src/datadog-labs/agent-skills
  env:
    - ATLASSIAN_API_TOKEN
    - ATLASSIAN_EMAIL
    - ATLASSIAN_URL
    - DD_API_KEY
    - DD_APP_KEY
    - DD_SITE
    - KNAUF_OKTA_USERNAME
    - KNAUF_OKTA_PASSWORD
